### ISSUE TITLE
HOPS Alignment

### ISSUE THREAD

**Issue by ExoClock-adrian** [ExoWorldsSpies/hops#19]
HOPS stalled at start of Alignment ('Choosing calibrating stars'.) No stars are selected and progress remains at 0%.  Required a forced exit from command log.  Log shows an IndexError.

I tried deleting the first image file in the sequence and the problem did not occur. The only significant difference between first and second images I could see was a small patch of saturated pixels (cosmic ray?) around position (2407,1068) in the first image. When I restored the first image with the defect cloned out, the problem did not occur.
Image (as JPG) and HOPS log attached.

![KELT-17b-001R30](https://user-images.githubusercontent.com/121268250/222864208-430ea317-48ec-4fb5-8fc4-261d4d5fb7d5.jpg)

[HOPS log.txt](https://github.com/ExoWorldsSpies/hops/files/10887145/HOPS.log.txt)

**Comment by atsiaras** [comment]
Hopefully fixed in v3.1.1 - I will keep this issue open until you confirm it has been fixed.

**Comment by ExoClock-adrian** [comment]
Hi Angelos.

The alignment problem I reported does not occur in V3.1.1 with the same data 🙂.

Adrian
