### ISSUE TITLE
Photometry Window - Zoom in and sky annulus drawing

### ISSUE THREAD

**Issue by mdeldem** [ExoWorldsSpies/hops#2]
In the Photometry Window, when zoom in, the aperture radius is well drawing but the sky annulus drawing is not correctly rendered with a large zoom in.
HOPS version 2.6
![zoom_out](https://user-images.githubusercontent.com/17035330/78230722-08558d00-74d2-11ea-99c7-d764999125bd.png)
![zoom_in](https://user-images.githubusercontent.com/17035330/78230729-0a1f5080-74d2-11ea-83bf-8f2c0aac997f.png)

**Comment by atsiaras** [comment]
The yellow circles do not represent the sky annulus. They are just marking the stars that have similar flux with the selected target.

**Comment by mdeldem** [comment]
Okay, my apologies. Thank for this clarification.
