### ISSUE TITLE
Twirl dependency breaking new installations

### ISSUE THREAD

**Issue by aretselis** [ExoWorldsSpies/hops#20]
Trying to troubleshoot an installation for a user (on version v3.1.1 of hops), we discovered that the `twirl` package dependency definition breaks new installations.

In `setup.py` ([link](https://github.com/ExoWorldsSpies/hops/blob/master/setup.py)), no version is defined for twirl so it attempts to install the latest available (currently version 0.3.2 at the time of writing this issue). Seems like they changed something in the twirl package and it breaks one of your modules.

The last available twirl version that appears to be working with hops is `twirl==0.1.3`. Recommending to either pin that version or fix the breaking change when running hops.

@gpantelidou please attach the error you are getting to see if it worth the effort fixing it immediately instead of pinning the twirl version.

**Comment by gpantelidou** [comment]
<img width="859" alt="WindowsTerminal_9IRn4uzEWf" src="https://github.com/ExoWorldsSpies/hops/assets/82615471/358aed48-15a8-4e08-b02d-80c2c105033d">

**Comment by atsiaras** [comment]
Thanks for the notice! I have pinned  the version for the moment in the latest commit.
