### ISSUE TITLE
What is parameter N0, L0, and Q0 in the fitting result?

### ISSUE THREAD

**Issue by ridlo** [ExoWorldsSpies/hops#8]
Hi, 

I am new to HOPS and exoplanet transit observation, what is parameter N0, L0, and Q0 in the fitting result? I could not find the explanation in the manual/code.

**Comment by atsiaras** [comment]
Hi, you can find the description in the fitting_output_description.txt file that is saved inside the PHOTOMETRY_APERTURE_FITTING or PHOTOMETRY_GAUS_FITTING directories.

The N0, L0, Q0 are the 0th, 1st and 2nd order coefficient of the de-trending function. In the latest version (v3.1), they have been renamed to c0, c1, c2, respectively
